shared_desktop/prog/urls.py
"""board URL configuration."""
from django.urls import path

from . import views


app_name = "prog"

urlpatterns = [
    path(
        "",
        views.prog,
        name="prog"
    ),
    path(
        "passport/equipment_layout/",
        views.equipment_layout,
        name="equipment_layout"
    ),
    path(
        "passport/table_of_directions/",
        views.table_of_directions,
        name="table_of_directions"
    ),
    path(
        "passport/phase_images/",
        views.phase_images,
        name="phase_images"
    ),
    path(
        "passport/fixed_program_tables/",
        views.fixed_program_tables,
        name="fixed_program_tables"
    ),
    path(
        "passport/the_layout_of_the_detectors/",
        views.the_layout_of_the_detectors,
        name="the_layout_of_the_detectors"
    ),
    path(
        "passport/table_of_detectors/",
        views.table_of_detectors,
        name="table_of_detectors"
    ),
    path(
        "passport/monitoring_of_peripheral_equipment/",
        views.monitoring_of_peripheral_equipment,
        name="monitoring_of_peripheral_equipment"
    ),
    path(
        "passport/phase_alternation/",
        views.phase_alternation,
        name="phase_alternation"
    ),
    path(
        "passport/adaptive_program_tables/",
        views.adaptive_program_tables,
        name="adaptive_program_tables"
    ),
]

shared_desktop/shared_desktop/urls.py
"""shared desktop URL configuration."""
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("tools.urls", namespace="tools")),
    path("index/", include("board.urls")),
    path("prog/", include("prog.urls")),
    path("tools/", include("tools.urls", namespace="tools_root")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path(r'api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
]

handler403 = 'board.views.handler403'
handler404 = 'board.views.handler404'
handler500 = 'board.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shared_desktop/tools/urls.py
"""tools URL configuration."""

from django.urls import path, include

from .toolkit import views

from . import (
    api_dir, calculate_cycle, dt_potok, excel_phase_count,
    excel_sg_count_model, phase_control, restart_web_admin,
    views, open_py_xl, crcpeek, swarco_log,
    get_firmware, swarco_ssh, dt_potok2
)
from .open_py_xl import OpenpyxlAPIView
from .swarco_log import SwarcoLogView
from .tab_dt_gen import GenerateDetectorTable
from .tab_com_gen import GenerateSwitchTable, ReadPdfPassport
from .toolkit.views import (
    ControllerManagementAPI,
    DownloadConfig,
    TrafficLightsUpdate,
    ManageControllers,
    SearchByNumberTrafficLightsAPIVeiw,
    CompareGroups,
    CompareGroupsAPI,
    PotokTrafficLightsConfigurator,
    PotokTrafficLightsConfiguratorAPI,
    ConflictsAndStagesAPI,
    ConflictsAndStages, PeekProcesses
)
from .toolkit.routers import router_controller_managemet
from .controller_preset import PresetListCreateView, PresetDetailView


app_name = "tools"

urlpatterns = [
    path("", api_dir.api_dir, name="api_dir"),
    path("tools", views.tools, name="tools"),
    path(
        "calculate_cycle/",
        calculate_cycle.calculate_cycle,
        name="calculate_cycle",
    ),
    path(
        "phase_control/",
         phase_control.phase_control,
         name="phase_control"
    ),
    path(
        "restart_web_admin/",
        restart_web_admin.restart_web_admin,
        name="restart_web_admin",
    ),
    path(
        "excel_phase_count/",
        excel_phase_count.excel_phase_count,
        name="excel_phase_count",
    ),
    path(
        "excel_sg_count_model/",
        excel_sg_count_model.excel_sg_count_model,
        name="excel_sg_count_model",
    ),
    path("api/restart_web_admin/", restart_web_admin.restart_web_admin_api, name="restart_web_admin_api"),
    path("api_dir/", api_dir.api_dir, name="api_dir"),
    path("controllers_status_check/", api_dir.controllers_status_check, name="controllers_status_check"),
    path("swarco_ssh/", swarco_ssh.swarco_ssh, name="swarco_ssh"),
    path('execute_top/', swarco_ssh.execute_top, name='execute_top'),
    path('execute_ps/', swarco_ssh.execute_ps, name='execute_ps'),
    path('execute_kill/', swarco_ssh.execute_kill, name='execute_kill'),
    path("dt_potok/", dt_potok.dt_potok, name="dt_potok"),
    path('dt_potok_api/', dt_potok.dt_potok_api, name='dt_potok_api'),
    path('dt_potok2_api/', dt_potok2.dt_potok2_api, name='dt_potok2_api'),
    path('get_phase/', phase_control.get_phase, name='get_phase'),
    path('set_phase/', phase_control.set_phase, name='set_phase'),

    path('openpyxl/', open_py_xl.openpyxl, name='openpyxl'),
    path('api/openpyxl/', OpenpyxlAPIView.as_view(), name='openpyxl-api'),
    path('api/parameter-sets/<str:name>/', OpenpyxlAPIView.as_view(), name='parameter-sets-detail'),
    path('crcpeek/', crcpeek.crcpeek, name='crcpeek'),
    path('api/crcpeek/', crcpeek.api_crcpeek, name='api_crcpeek'),
    path('swarco_log/', swarco_log.swarco_log, name='swarco_log'),
    path('swarco_log_api/', SwarcoLogView.as_view(), name='api_swarco_log'),
    path('get_firmware/', get_firmware.get_firmware, name='get_firmware'),
    path('get_firmware_api/', get_firmware.get_firmware_api, name='get_firmware_api'),
    path('generate-detector-table/', GenerateDetectorTable.as_view(), name='generate-detector-table'),

    path('generate-switch-table/', GenerateSwitchTable.as_view(), name='generate-switch-table'),
    path('read-pdf-passport/', ReadPdfPassport.as_view(), name='read-pdf-passport'),

    path("manage_controllers/", ManageControllers.as_view(), name='manage_controllers'),
    path("download_config/", DownloadConfig.as_view(), name='download_config'),
    path('calc_conflicts/', ConflictsAndStages.as_view(), name='calc_conflicts'),
    path("passport/", CompareGroups.as_view(), name="passport"),
    path("tlc_potok/", PotokTrafficLightsConfigurator.as_view(), name="tlc_potok"),
    path("api/v1/manage-controller/", ControllerManagementAPI.as_view()),
    path("api/v1/download-config/", ControllerManagementAPI.as_view()),
    path("api/v1/conflicts/", ConflictsAndStagesAPI.as_view()),
    path('api/v1/trafficlight-objects/<str:number>', SearchByNumberTrafficLightsAPIVeiw.as_view()),
    path('api/v1/update_trafficlihgtdata/', TrafficLightsUpdate.as_view()),
    path("api/v1/compare-groups/", CompareGroupsAPI.as_view()),
    path("api/v1/potok-tlc/", PotokTrafficLightsConfiguratorAPI.as_view()),
    path("api/v1/peek-processes/", PeekProcesses.as_view()),
    path("api/v1/", include(router_controller_managemet.urls)),


    path('api/presets/', PresetListCreateView.as_view(), name='preset-list'),
    path('api/presets/<int:pk>/', PresetDetailView.as_view(), name='preset-detail'),
]

shared_desktop/tools/toolkit/views.py
from time import process_time_ns
from typing import Generator

from django.core.files.uploadedfile import InMemoryUploadedFile
from django.views.generic import TemplateView
from rest_framework import generics, viewsets
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework.response import Response
import json
import logging
import time
import asyncio
import openpyxl
from io import BytesIO

from .models import ControllerManagement, TrafficLightsObjects
from . import services as services
from .serializers import BaseTrafficLightsSerializer, ControllerHostsSerializer
from .constants import RequestOptions, AvailableTypesRequest

logger = logging.getLogger(__name__)

TYPES_CONTROLLER = ['Swarco', 'Поток (S)', 'Поток (P)', 'Peek']

"""" API  """


class ControllerManagementHostsConfigurationViewSetAPI(viewsets.ModelViewSet):
    queryset = ControllerManagement.objects.all()
    serializer_class = ControllerHostsSerializer
    lookup_field = 'name'


class SearchByNumberTrafficLightsAPIVeiw(generics.RetrieveAPIView):
    queryset = TrafficLightsObjects.objects.all()
    serializer_class = BaseTrafficLightsSerializer
    lookup_field = 'number'


class TrafficLightsUpdate(APIView):
    """
    Обновляет модель светофорных объектов.
    SQL, который сбрасывает счетчик авто-инкремента pk:
    ALTER SEQUENCE toolkit_trafficlightsobjects_id_seq RESTART WITH 1;
    """

    # permission_classes = (IsAdminUser,)

    FILENAME = 'List'
    ALLOWED_FILE_EXT = {'xls', 'xlsx'}

    ID               = 0
    NUMBER           = 1
    TYPE_CONTROLLER  = 2
    ADDRESS          = 3
    LONGITUDE        = 4
    LATITUDE         = 5
    REGION           = 6
    DESCRIPTION      = 7
    IP_ADDRESS       = 8

    bad_response = {
        'result': 'Некорректное имя файла и/или расширение, данные не обновлены',
        'ok': False
    }
    good_response ={
        'result': 'Данные не обновлены',
        'ok': True
    }
    matches_controllers_to_group = {
        'Swarco': 1,
        'Peek': 2,
        'Поток (P)': 3,
        'Поток (S)': 4,
        'Сигнал (STCIP)': 5,
        'Сигнал (SXTP)': 6,
        'ДКС': 7,
        'ДКС (Старт)': 8,
        'ДКСТ': 9,
    }

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._request = None
        self.wb = None
        self.sheet = None

    def post(self, request):
        start_time = time.time()
        logger.debug(request.FILES)
        if not self.check_filename(request.FILES['file'].name):
            return Response(self.bad_response)
        self.wb = openpyxl.load_workbook(filename=BytesIO(request.FILES['file'].read()))
        self.sheet = self.wb.active

        TrafficLightsObjects.objects.all().delete()
        TrafficLightsObjects.objects.bulk_create(self.get_model_objects())
        logger.debug(f'Время обновления: {(time.time() - start_time)}')
        print(f'Время обновления: {(time.time() - start_time)}')
        return Response(self.good_response)

    def get_model_objects(self) -> Generator:
        it = self.sheet.iter_rows()
        next(it) # Пропустить первую row, которая является шапкой excel таблицы
        return (
            TrafficLightsObjects(
                id=row_cells[self.ID].value,
                number=row_cells[self.NUMBER].value,
                address=row_cells[self.ADDRESS].value,
                description=row_cells[self.DESCRIPTION].value,
                ip_adress=row_cells[self.IP_ADDRESS].value,
                type_controller=row_cells[self.TYPE_CONTROLLER].value,
                group=self.matches_controllers_to_group.get(row_cells[self.TYPE_CONTROLLER].value, 0)
            )
            for row_cells in it
        )

    def check_filename(self, full_filename: str) -> bool:
        splitter = '.'
        _full_filename = full_filename.split(splitter)
        if len(_full_filename) < 2:
            return False
        name, _extension = splitter.join(_full_filename[:-1]), _full_filename[-1]
        if _extension not in self.ALLOWED_FILE_EXT or name != self.FILENAME:
            return False
        return True


class ControllerManagementAPI(APIView):
    """
    Управление/получение данных/загрузка конфига с контроллеров
    """

    def post(self, request):

        start_time = time.time()
        data_body = request.data
        logger.debug(data_body)
        data_hosts_body, type_req, req_from_telegramm, chat_id, search_in_db = (
            data_body.get(RequestOptions.hosts.value),
            data_body.get(RequestOptions.type_request.value),
            data_body.get(RequestOptions.request_from_telegramm.value),
            data_body.get(RequestOptions.chat_id.value),
            data_body.get(RequestOptions.search_in_db.value)
        )
        logger.debug(data_hosts_body)
        if (data_hosts_body is None or type_req is None or type_req not in
                AvailableTypesRequest.TYPE_GET.value | AvailableTypesRequest.TYPE_SET.value):
            return Response({'detail': services.ErrorMessages.BAD_DATA_FOR_REQ.value})

        db = services.QuerysetToDB()
        if req_from_telegramm is not None:
            if chat_id is None:
                return Response({'detail': services.ErrorMessages.BAD_DATA_FOR_REQ.value})
            chat_id_is_valid = asyncio.run(db.get_queryset_chat_id_tg(chat_id))
            if chat_id_is_valid is None:
                return Response({'detail': services.ErrorMessages.BAD_DATA_FOR_REQ.value})

        responce_manager = services.ResponceMaker()
        checker = services.Checker()

        data_hosts = responce_manager.create_base_struct(data_hosts_body)
        logger.debug(data_hosts)

        if search_in_db:
            data_hosts = asyncio.run(db.main(data_hosts))
            logger.debug('data_hosts_for_req_after_req_to_db')
            logger.debug(data_hosts)
        else:
            data_hosts = data_hosts_body

        responce_manager.save_json_to_file(data_hosts, 'data_hosts_after_queryset.json')
        logger.debug(data_hosts)
        data_hosts = checker.validate_all_properties_data_hosts(data_hosts, type_req)
        logger.debug(data_hosts)
        if checker.check_error_request_in_all_hosts(data_hosts):
            return Response(data_hosts)
        controller_manager = services.get_controller_manager(type_req)
        if controller_manager is None:
            return Response({'detail': services.ErrorMessages.BAD_DATA_FOR_REQ.value})

        data_hosts = asyncio.run(controller_manager.main(data_hosts))
        if type_req == RequestOptions.type_get_config.value:
            logger.debug(data_hosts)
            data_hosts = controller_manager.create_zip_archive_and_save_to_db_multiple(data_hosts)
            if checker.check_error_request_in_all_hosts(data_hosts):
                return Response(responce_manager.add_end_time_to_data_hosts(data_hosts))
            if req_from_telegramm:
                send_file_tg = services.TelegrammBot()
                data_hosts = asyncio.run(
                    send_file_tg.main(data_hosts, chat_id, send_file=True)
                )
            data_hosts = responce_manager.remove_prop(data_hosts, (services.JsonResponceBody.MODEL_OBJ.value,))
            logger.debug(data_hosts)

        responce_manager.save_json_to_file(data_hosts)
        logger.debug(f'Время выполнения запроса: {time.time() - start_time}')
        return Response(data_hosts)


class GetFileFromControllerAPI(APIView):

    def post(self, request):

        start_time = time.time()
        logger.debug(request.data)
        data_body = request.data
        data_hosts_body, type_req, chat_id = (
            request.data.get('hosts'), request.data.get('type_request'), request.data.get('chat_id')
        )
        logger.debug(data_hosts_body)
        if not data_hosts_body or not type_req or not chat_id:
            return Response({'detail': services.ErrorMessages.BAD_DATA_FOR_REQ.value})

        responce_manager = services.ResponceMaker()
        db = services.QuerysetToDB()

        chat_idIsvalid = asyncio.run(db.get_queryset_chat_id_tg(chat_id))
        if chat_idIsvalid is None or chat_idIsvalid.get('chat_id') is None:
            return Response({'detail': services.ErrorMessages.BAD_DATA_FOR_REQ.value})
        logger.debug(chat_idIsvalid)
        logger.debug(chat_idIsvalid['chat_id'])

        needQueryset = request.data.get(services.RequestOptions.search_in_db.value)
        if needQueryset:

            data_hosts_for_req = db.get_parsed_data(data_hosts_body)
            logger.debug('data_hosts_for_req_after_req_to_db')
            logger.debug(data_hosts_for_req)

        else:
            # Тут должна быть проверка, что передан именно IP-адресс и допустимый тип контроллера
            data_hosts_for_req = data_hosts_body

        if services.check_error_request_in_all_hosts(data_hosts_for_req):
            return Response({'detail': services.ErrorMessages.BAD_DATA_FOR_REQ.value})

        manager = services.DownLoadFile()
        res_download = asyncio.run(manager.download_file(data_hosts_for_req))

        logger.debug(res_download)
        data_hosts_for_req = manager.create_zip_archive_and_save_to_db_multiple(
            data_hosts_for_req, res_download
        )

        # logger.debug(data_hosts_for_req)
        if services.check_error_request_in_all_hosts(data_hosts_for_req):
            responce = responce_manager.create_json(
                data_hosts_for_req, start_time
            )
            return Response(responce)

        send_file_tg = services.TelegrammBot()
        res_send_file = asyncio.run(send_file_tg.main(data_hosts_for_req, [
            (ipAddr, data_body.get('chat_id'), data_host.get('path_to_archive'))
            for ipAddr, data_host in data_hosts_for_req.items()
        ], send_file=True
                                                      ))

        logger.debug(res_send_file)

shared_desktop/tools/views.py
from django.shortcuts import render


def tools(request):
    """Инструменты."""
    template = "tools/tools.html"
    tools = "tools"
    context = {
        "tools": tools,
    }
    return render(request, template, context)

shared_desktop/templates/tools/calc_conflicts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="container">
        <div class="row">

        {% include 'tools_sidebar.html' %}

        <div class="col-md-8">
          <h2>Расчет конфликтов</h2>

          <!-- Инструкция -->
          <div class="alert alert-light">
            <h4>Инструкция:</h4>
            <ul>
              <li>Введите направления для каждой фазы в отдельной строке. 
              <li>Перед направлениями можно, при необходимости добавить текст, за которым следует двоеточие, например: <code>Фаза1:1,2,3</code>.</li>
              <li>Выберите тип контроллера, если он применим.</li>
              <li>Отметьте опции для создания файлов конфигурации и конфликтов по необходимости.</li>
              <li>Нажмите "Отправить" для генерации матрицы конфликтов и файлов конфигурации.</li>
            </ul>
          </div>

            {% csrf_token %}
            <div class="calc_conflicts" id="controllers">
                <label class="calc_conflicts_controllers" id="testtt"> Тип ДК: </label>
                <input type="radio" value="common" name="controller_type" checked id="common">
                <label for="common">Общий</label>
                <input type="radio" value="swarco" name="controller_type" id="swarco">
                <label for="swarco">Swarco</label>
                <input type="radio" value="peek" name="controller_type" id="peek">
                <label for="peek">Peek</label>
            </div>
            <br><br>

            <fieldset>
                <legend> Опции </legend>
                <div>
                    <input type="checkbox" name="create_txt" id="create_txt">
                    <label class="calc_conflicts_optinos" for="create_txt"> Создать txt файл с конфликтами: </label>
                </div>
                <div>
                    <input type="checkbox" name="binval_swarco" id="binval_swarco" disabled>
                    <label class="calc_conflicts_optinos" for="binval_swarco"> Матрица конфликтов и бинарные значения фаз для swarco</label>
                </div>
                <div>
                    <input type="checkbox" name="make_config" id="make_config" disabled>
                    <label class="calc_conflicts_optinos" for="make_config"> Создать файл конфигурации: </label>
                    <input type="file" id="config_file" name="upload_config_file" multiple disabled>
                </div>
            </fieldset>
            <br>

            <table id="user_data">
                <tr>
                    <th>Введите фазы-направления</th>
                    <th>Результат ввода</th>
                    <th>Ошибки ввода:</th>
                </tr>

                <tr id="user_content">
                    <td id="td_textarea_user_input">
                        <textarea name="table_stages" id="stages_from_area"></textarea>
                    </td>
                    <td id="pretty_output_stages"></td>
                    <td id="td_errors">

                    </td>
                </tr>
            </table>

            <p></p>

            <!--<div id="pretty_output_stages"> </div>-->

            <button title="" id="send_conflicts_data"> Отправить </button>
            <p></p>



            <div id="calculated_content"></div>

            <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="{% static 'js/toolkit_conflicts.js'%}"></script>

        </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

shared_desktop/templates/tools/crcpeek.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="container">
      <div class="row">
        {% include 'tools_sidebar.html' %}
        <div class="col-md-8">
          <h2>Расчет контрольной суммы RAG</h2>
          <form id="upload-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group row mb-1">
              <div class="col-md-12">
                <input type="file" class="form-control" id="file" name="file" required onchange="document.getElementById('upload-form').submit();">
              </div>
            </div>
          </form>

          {% if file_content %}
          <form id="process-form" method="post">
            {% csrf_token %}
            <div class="form-group mt-3">
              <label for="file-content">Содержимое файла</label>
              <textarea class="form-control" id="file-content" name="file_content" rows="15" style="font-family: monospace;">{{ file_content }}</textarea>
              <input type="hidden" name="initial_crc" value="{{ initial_crc }}">
              <input type="hidden" name="sum_in_file" value="{{ sum_in_file }}">
            </div>
            <div class="form-group mt-2">
              <button type="submit" class="btn btn-primary" name="action" value="process">Процесс</button>
              <button type="submit" class="btn btn-success" name="action" value="save">Сохранить</button>
            </div>
          </form>
          <div class="alert alert-info mt-3">
            {% comment %} <strong>Начальная контрольная сумма:</strong> {{ initial_crc }}<br>
            <strong>Текущая контрольная сумма:</strong> {{ crc_sum }}<br> {% endcomment %}
            <strong>Разница контрольной суммы:</strong> {% if crc_diff is not None %}{{ crc_diff }}{% else %}0{% endif %}<br>
            <strong>Сумма в файле:</strong> {{ sum_in_file }}<br>
            <strong>Новая сумма в файле:</strong> {% if new_sum_in_file is not None %}{{ new_sum_in_file }}{% else %}0{% endif %}
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

<script>
document.getElementById('file').addEventListener('change', function() {
    document.getElementById('upload-form').submit();
});
</script>
{% endblock %}

shared_desktop/templates/tools/swarco_ssh.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="container">
      <div class="row">

        {% include 'tools_sidebar.html' %}

        <!-- Правая часть страницы -->
        <div class="col-md-8">
          <h2>Сброс сессий пользователя 'itc' на Swarco</h2>

          <form id="ssh-form" method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-3" style="width: 27%;">
                <input type="text" class="form-control" id="ip" name="ip" placeholder="Введите IP адрес" value="{{ request.POST.ip }}" required>
              </div>

              <div class="col-md-2" style="width: 12%;">
                  <button type="button" id="ps-button" class="btn btn-secondary">Показать</button>
              </div>

              <div class="col-md-3">
                  <button type="button" id="kill-button" class="btn btn-danger">Сбросить</button>
              </div>

            <div class="col-md-2">
              <button type="button" id="top-button" class="btn btn-primary" style="visibility: hidden;">Список процессов</button>
            </div>
          </div>
          </form>
          
          <!-- Результат выполнения команд -->
          <div id="top-output" class="mt-4">
            <pre id="output"></pre>
          </div>
          
          <div id="ps-output" class="mt-4">
            <pre id="ps-result"></pre>
          </div>
          

        </div>
      </div>
    </div>
  </div>
</div>

<script>
  // Функция для проверки формата IP-адреса
  function isValidIP(ip) {
    const ipRegex = /^(25[0-5]|2[0-4][0-9]|[0-1]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[0-1]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[0-1]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[0-1]?[0-9][0-9]?)$/;
    return ipRegex.test(ip);
  }

  // Общая функция проверки IP перед выполнением действия
  function validateAndProceed(ip, callback) {
    if (ip && isValidIP(ip)) {
      callback();
    } else {
      alert("Введите корректный IP адрес в формате XXX.XXX.XXX.XXX");
    }
  }

  // Событие для кнопки "Список процессов"
  document.getElementById('top-button').addEventListener('click', function () {
    const ip = document.getElementById('ip').value;
    validateAndProceed(ip, function () {
      // Выполним асинхронный запрос на сервер для команды top
      fetch("{% url 'tools:execute_top' %}", {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
        },
        body: JSON.stringify({ ip: ip })
      })
        .then(response => response.json())
        .then(data => {
          if (data.success) {
            document.getElementById('output').textContent = data.result;
          } else {
            document.getElementById('output').textContent = "Ошибка выполнения команды.";
          }
        })
        .catch(error => {
          console.error('Ошибка:', error);
          document.getElementById('output').textContent = "Ошибка запроса.";
        });
    });
  });

  // Событие для кнопки "Показать"
  document.getElementById('ps-button').addEventListener('click', function () {
    const ip = document.getElementById('ip').value;
    validateAndProceed(ip, function () {
      // Выполним асинхронный запрос на сервер для команды ps
      fetch("{% url 'tools:execute_ps' %}", {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
        },
        body: JSON.stringify({ ip: ip })
      })
        .then(response => response.json())
        .then(data => {
          if (data.success) {
            document.getElementById('ps-result').textContent = data.result;
          } else {
            document.getElementById('ps-result').textContent = "Ошибка выполнения команды.";
          }
        })
        .catch(error => {
          console.error('Ошибка:', error);
          document.getElementById('ps-result').textContent = "Ошибка запроса.";
        });
    });
  });

  // Событие для кнопки "Сбросить"
  document.getElementById('kill-button').addEventListener('click', function () {
    const ip = document.getElementById('ip').value;
    validateAndProceed(ip, function () {
      // Выполним асинхронный запрос на сервер для команды kill
      fetch("{% url 'tools:execute_kill' %}", {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value
        },
        body: JSON.stringify({ ip: ip })
      })
        .then(response => response.json())
        .then(data => {
          if (data.success) {
            document.getElementById('ps-result').textContent = data.result;
          } else {
            document.getElementById('ps-result').textContent = "Ошибка выполнения команды.";
          }
        })
        .catch(error => {
          console.error('Ошибка:', error);
          document.getElementById('ps-result').textContent = "Ошибка запроса.";
        });
    });
  });
</script>


{% endblock %}