shared_desktop/board/urls.py
"""board URL configuration."""
from django.urls import path

from . import views
from .views import RuleListAPIView


app_name = "rules"

urlpatterns = [
    path("", views.index, name="rules"),
    path("full/", views.full, name="full"),
    path("rules/", views.rules_list, name="rule"),
    path("rules/<pk>/", views.rules_detail),
    path('api/rules/', RuleListAPIView.as_view(), name='rule-list'),
]

shared_desktop/prog/urls.py
"""board URL configuration."""
from django.urls import path

from . import views


app_name = "prog"

urlpatterns = [
    path(
        "",
        views.prog,
        name="prog"
    ),
    path(
        "passport/equipment_layout/",
        views.equipment_layout,
        name="equipment_layout"
    ),
    path(
        "passport/table_of_directions/",
        views.table_of_directions,
        name="table_of_directions"
    ),
    path(
        "passport/phase_images/",
        views.phase_images,
        name="phase_images"
    ),
    path(
        "passport/fixed_program_tables/",
        views.fixed_program_tables,
        name="fixed_program_tables"
    ),
    path(
        "passport/the_layout_of_the_detectors/",
        views.the_layout_of_the_detectors,
        name="the_layout_of_the_detectors"
    ),
    path(
        "passport/table_of_detectors/",
        views.table_of_detectors,
        name="table_of_detectors"
    ),
    path(
        "passport/monitoring_of_peripheral_equipment/",
        views.monitoring_of_peripheral_equipment,
        name="monitoring_of_peripheral_equipment"
    ),
    path(
        "passport/phase_alternation/",
        views.phase_alternation,
        name="phase_alternation"
    ),
    path(
        "passport/adaptive_program_tables/",
        views.adaptive_program_tables,
        name="adaptive_program_tables"
    ),
]

shared_desktop/shared_desktop/urls.py
"""shared desktop URL configuration."""
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("tools.urls", namespace="tools")),
    path("index/", include("board.urls")),
    path("prog/", include("prog.urls")),
    path("tools/", include("tools.urls", namespace="tools_root")),
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path(r'api/v1/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),
]

handler403 = 'board.views.handler403'
handler404 = 'board.views.handler404'
handler500 = 'board.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shared_desktop/tools/urls.py
"""tools URL configuration."""

from django.urls import path, include

from .toolkit import views

from . import (
    api_dir, calculate_cycle, dt_potok, excel_phase_count,
    excel_sg_count_model, phase_control, restart_web_admin,
    views, open_py_xl, crcpeek, swarco_log,
    get_firmware, swarco_ssh, dt_potok2
)
from .open_py_xl import OpenpyxlAPIView
from .swarco_log import SwarcoLogView
from .tab_dt_gen import GenerateDetectorTable
from .tab_com_gen import GenerateSwitchTable, ReadPdfPassport
from .toolkit.views import (
    ControllerManagementAPI,
    DownloadConfig,
    TrafficLightsUpdate,
    ManageControllers,
    SearchByNumberTrafficLightsAPIVeiw,
    CompareGroups,
    CompareGroupsAPI,
    PotokTrafficLightsConfigurator,
    PotokTrafficLightsConfiguratorAPI,
    ConflictsAndStagesAPI,
    ConflictsAndStages, PeekProcesses
)
from .toolkit.routers import router_controller_managemet
from .controller_preset import PresetListCreateView, PresetDetailView


app_name = "tools"

urlpatterns = [
    path("", api_dir.api_dir, name="api_dir"),
    path("tools", views.tools, name="tools"),
    path(
        "calculate_cycle/",
        calculate_cycle.calculate_cycle,
        name="calculate_cycle",
    ),
    path(
        "phase_control/",
         phase_control.phase_control,
         name="phase_control"
    ),
    path(
        "restart_web_admin/",
        restart_web_admin.restart_web_admin,
        name="restart_web_admin",
    ),
    path(
        "excel_phase_count/",
        excel_phase_count.excel_phase_count,
        name="excel_phase_count",
    ),
    path(
        "excel_sg_count_model/",
        excel_sg_count_model.excel_sg_count_model,
        name="excel_sg_count_model",
    ),
    path("api/restart_web_admin/", restart_web_admin.restart_web_admin_api, name="restart_web_admin_api"),
    path("api_dir/", api_dir.api_dir, name="api_dir"),
    path("controllers_status_check/", api_dir.controllers_status_check, name="controllers_status_check"),
    path("swarco_ssh/", swarco_ssh.swarco_ssh, name="swarco_ssh"),
    path('execute_top/', swarco_ssh.execute_top, name='execute_top'),
    path('execute_ps/', swarco_ssh.execute_ps, name='execute_ps'),
    path('execute_kill/', swarco_ssh.execute_kill, name='execute_kill'),
    path("dt_potok/", dt_potok.dt_potok, name="dt_potok"),
    path('dt_potok_api/', dt_potok.dt_potok_api, name='dt_potok_api'),
    path('dt_potok2_api/', dt_potok2.dt_potok2_api, name='dt_potok2_api'),
    path('get_phase/', phase_control.get_phase, name='get_phase'),
    path('set_phase/', phase_control.set_phase, name='set_phase'),

    path('openpyxl/', open_py_xl.openpyxl, name='openpyxl'),
    path('api/openpyxl/', OpenpyxlAPIView.as_view(), name='openpyxl-api'),
    path('api/parameter-sets/<str:name>/', OpenpyxlAPIView.as_view(), name='parameter-sets-detail'),
    path('crcpeek/', crcpeek.crcpeek, name='crcpeek'),
    path('api/crcpeek/', crcpeek.api_crcpeek, name='api_crcpeek'),
    path('swarco_log/', swarco_log.swarco_log, name='swarco_log'),
    path('swarco_log_api/', SwarcoLogView.as_view(), name='api_swarco_log'),
    path('get_firmware/', get_firmware.get_firmware, name='get_firmware'),
    path('get_firmware_api/', get_firmware.get_firmware_api, name='get_firmware_api'),
    path('generate-detector-table/', GenerateDetectorTable.as_view(), name='generate-detector-table'),

    path('generate-switch-table/', GenerateSwitchTable.as_view(), name='generate-switch-table'),
    path('read-pdf-passport/', ReadPdfPassport.as_view(), name='read-pdf-passport'),

    path("manage_controllers/", ManageControllers.as_view(), name='manage_controllers'),
    path("download_config/", DownloadConfig.as_view(), name='download_config'),
    path('calc_conflicts/', ConflictsAndStages.as_view(), name='calc_conflicts'),
    path("passport/", CompareGroups.as_view(), name="passport"),
    path("tlc_potok/", PotokTrafficLightsConfigurator.as_view(), name="tlc_potok"),
    path("api/v1/manage-controller/", ControllerManagementAPI.as_view()),
    path("api/v1/download-config/", ControllerManagementAPI.as_view()),
    path("api/v1/conflicts/", ConflictsAndStagesAPI.as_view()),
    path('api/v1/trafficlight-objects/<str:number>', SearchByNumberTrafficLightsAPIVeiw.as_view()),
    path('api/v1/update_trafficlihgtdata/', TrafficLightsUpdate.as_view()),
    path("api/v1/compare-groups/", CompareGroupsAPI.as_view()),
    path("api/v1/potok-tlc/", PotokTrafficLightsConfiguratorAPI.as_view()),
    path("api/v1/peek-processes/", PeekProcesses.as_view()),
    path("api/v1/", include(router_controller_managemet.urls)),


    path('api/presets/', PresetListCreateView.as_view(), name='preset-list'),
    path('api/presets/<int:pk>/', PresetDetailView.as_view(), name='preset-detail'),
]

shared_desktop/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path


app_name = "users"

urlpatterns = [
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
]

shared_desktop/templates/includes/footer.html
{% load static %}
{% now "Y" as current_year %}

<div class="container d-flex justify-content-end">
  <div class="ml-auto">
    <span style="font-size: 10px;">СпецДорПроект {{ current_year }}</span>
  </div>
</div>

shared_desktop/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-light" style="background-color: black">
{% with request.resolver_match.view_name as view_name %}
    <div class="container">

      <a class="navbar-brand" href="{% url 'rules:rules' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:white">Рабочий стол транспортного инженера
      </a>

      <ul class="nav nav-tabs">

        <li class="nav-item"> 
          {% if view_name  == 'rules:full' %}
            <a class="nav-link active" href="{% url 'rules:rules' %}">Расширенный вид</a>
          {% elif view_name  == 'rules:rules' %}
            <a class="nav-link active" href="{% url 'rules:full' %}">Обычный вид</a>
          {% else %}
            <a class="nav-link" href="{% url 'rules:rules' %}">Главная</a>
          {% endif %}
        </li>

        <li class="nav-item">
          {% if view_name|slice:':5'  == 'prog:' %}
            <a class="nav-link active" href="{% url 'prog:prog' %}">Программирование ДК</a>
          {% else %}
            <a class="nav-link" href="{% url 'prog:prog' %}">Программирование ДК</a>
          {% endif %}
        </li>

        <li class="nav-item"> 
          
          {% if view_name|slice:':6' == 'tools:' %}
            <a class="nav-link active" href="{% url 'tools:tools' %}">Инструменты</a>
          {% else %}
            <a class="nav-link" href="{% url 'tools:tools' %}">Инструменты</a>
          {% endif %}
        </li>

        {% if user.is_authenticated %}

          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
          </li>

        {% else %}

          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
          </li>

        {% endif %}


          <li class="nav-item"> 
            <a class="nav-link link-light text-warning " href="http://192.168.45.66/" target="_blank">Новый сайт</a>
          </li>

        </ul>

</div>
{% endwith %} 